# Generated by Django 3.2.23 on 2024-03-15 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ppdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id_peserta', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('no_pendaftaran', models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='No Pendaftaran')),
                ('status', models.CharField(choices=[('Siswa Baru', 'Siswa Baru'), ('Pindahan', 'Pindahan')], default=1, max_length=10, verbose_name='Status')),
                ('nama', models.CharField(max_length=55, verbose_name='Nama Lengkap')),
                ('tempat_lahir', models.CharField(max_length=30, verbose_name='Tempat Lahir')),
                ('tgl_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('agama', models.CharField(choices=[('', 'Pilih agama'), ('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Kong Hu Cu', 'Kong Hu Cu')], max_length=10, verbose_name='Agama')),
                ('asal_sekolah', models.CharField(max_length=60, verbose_name='Asal Sekolah')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='', max_length=15, verbose_name='Jenis Kelamin')),
                ('anak_ke', models.CharField(blank=True, max_length=2, null=True, verbose_name='Anak Ke')),
                ('tlp_peserta', models.CharField(blank=True, help_text='Pastikan nomer aktif dan dapat dihubungi.', max_length=13, null=True, verbose_name='No Telp/Wa Peserta')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('verifikasi', models.CharField(choices=[('Pending', 'Pending'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Pending', max_length=10, null=True, verbose_name='Status Pendaftaran')),
                ('tgl_daftar', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Tanggal Daftar')),
                ('nama_ayah', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nama Lengkap Ayah')),
                ('pekerjaan_ayah', models.CharField(blank=True, choices=[('', 'Pekerjaan'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/POLRI', 'TNI/POLRI'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('wiraswasta', 'Wiraswasta'), ('Pengacara/Jaksa/Hakim/Notaris', 'Pengacara/Jaksa/Hakim/Notaris'), ('Seniman/Pelukis/Artis/Sejenis', 'Seniman/Pelukis/Artis/Sejenis'), ('Dokter/Bidan/Perawat', 'Dokter/Bidan/Perawat'), ('Pilot/Pramugara', 'Pilot/Pramugara'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh(Tani/Pabrik/Bangunan)', 'Buruh(Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('lainnya', 'Lainnya')], max_length=50, null=True, verbose_name='Pekerjaan Ayah')),
                ('nama_ibu', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nama Lengkap Ibu')),
                ('pekerjaan_ibu', models.CharField(blank=True, choices=[('', 'Pekerjaan'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/POLRI', 'TNI/POLRI'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('wiraswasta', 'Wiraswasta'), ('Pengacara/Jaksa/Hakim/Notaris', 'Pengacara/Jaksa/Hakim/Notaris'), ('Seniman/Pelukis/Artis/Sejenis', 'Seniman/Pelukis/Artis/Sejenis'), ('Dokter/Bidan/Perawat', 'Dokter/Bidan/Perawat'), ('Pilot/Pramugara', 'Pilot/Pramugara'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh(Tani/Pabrik/Bangunan)', 'Buruh(Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('lainnya', 'Lainnya')], max_length=30, null=True, verbose_name='Pekerjaan Ibu')),
                ('tlp_ortu', models.CharField(blank=True, help_text='Pastikan nomer aktif dan dapat dihubungi.', max_length=13, null=True, verbose_name='No Telp/Wa Orang Tua')),
                ('nama_wali', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nama Wali')),
                ('pekerjaan_wali', models.CharField(blank=True, choices=[('', 'Pekerjaan'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pensiunan', 'Pensiunan'), ('PNS', 'PNS'), ('TNI/POLRI', 'TNI/POLRI'), ('Guru/Dosen', 'Guru/Dosen'), ('Pegawai Swasta', 'Pegawai Swasta'), ('wiraswasta', 'Wiraswasta'), ('Pengacara/Jaksa/Hakim/Notaris', 'Pengacara/Jaksa/Hakim/Notaris'), ('Seniman/Pelukis/Artis/Sejenis', 'Seniman/Pelukis/Artis/Sejenis'), ('Dokter/Bidan/Perawat', 'Dokter/Bidan/Perawat'), ('Pilot/Pramugara', 'Pilot/Pramugara'), ('Pedagang', 'Pedagang'), ('Petani/Peternak', 'Petani/Peternak'), ('Nelayan', 'Nelayan'), ('Buruh(Tani/Pabrik/Bangunan)', 'Buruh(Tani/Pabrik/Bangunan)'), ('Sopir/Masinis/Kondektur', 'Sopir/Masinis/Kondektur'), ('Politikus', 'Politikus'), ('lainnya', 'Lainnya')], max_length=30, null=True, verbose_name='Pekerjaan Wali')),
                ('tlp_wali', models.CharField(blank=True, help_text='Pastikan nomer aktif dan dapat dihubungi.', max_length=13, null=True, verbose_name='No Telp/Wa Wali')),
                ('nisn', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siswa', to=settings.AUTH_USER_MODEL, verbose_name='NISN')),
            ],
            options={
                'verbose_name_plural': 'Peserta PPDB',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id_thn_ajaran', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('', 'Status PPDB'), ('Dibuka', 'Dibuka'), ('Ditutup', 'Ditutup')], max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Tahun Ajaran',
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id_prestasi', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('tingkat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tingkat')),
                ('kategori', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kategori')),
                ('juara', models.CharField(blank=True, max_length=255, null=True, verbose_name='Juara')),
                ('skor_prestasi', models.FloatField(blank=True, max_length=255, null=True, verbose_name='Skor Prestasi')),
                ('peserta', models.ManyToManyField(blank=True, related_name='prestasi', to='ppdb.Peserta')),
            ],
            options={
                'verbose_name_plural': 'Kategori Prestasi',
            },
        ),
        migrations.AddField(
            model_name='peserta',
            name='thn_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppdb.tahunajaran', verbose_name='Tahun Ajaran'),
        ),
        migrations.CreateModel(
            name='NilaiRaport',
            fields=[
                ('id_nilai_raport', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('smt_1', models.FloatField(verbose_name='Semester 1')),
                ('smt_2', models.FloatField(verbose_name='Semester 2')),
                ('smt_3', models.FloatField(verbose_name='Semester 3')),
                ('smt_4', models.FloatField(verbose_name='Semester 4')),
                ('smt_5', models.FloatField(verbose_name='Semester 5')),
                ('peserta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raport', to='ppdb.peserta')),
            ],
            options={
                'verbose_name_plural': 'Nilai Raport Peserta',
            },
        ),
        migrations.CreateModel(
            name='Berkas',
            fields=[
                ('id_berkas', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('file_kk', models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_kk, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Kartu Keluarga')),
                ('file_akta', models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_akta, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Akta Kelahiran')),
                ('file_raport', models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_raport, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Nilai Raport Terakhir')),
                ('file_skl', models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_skl, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Surat Keterangan Lulus')),
                ('file_ijazah', models.FileField(blank=True, help_text='(Jika sudah ada). File bisa berupa gambar atau pdf', max_length=255, null=True, upload_to=ppdb.models.Berkas.file_ijazah, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Ijazah Jenjang Sebelumnya')),
                ('file_skhun', models.FileField(blank=True, help_text='(Jika sudah ada). File bisa berupa gambar atau pdf', max_length=255, null=True, upload_to=ppdb.models.Berkas.file_skhun, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='SKHUN')),
                ('peserta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berkas', to='ppdb.peserta')),
            ],
            options={
                'verbose_name_plural': 'Berkas Siswa',
            },
        ),
    ]
