# Generated by Django 3.2.23 on 2023-12-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaturan_PPDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Dibuka', 'Dibuka'), ('Ditutup', 'Ditutup')], max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
            ],
            options={
                'verbose_name': 'Pengaturan PPDB',
                'verbose_name_plural': 'Pengaturan PPDB',
            },
        ),
    ]
