# Generated by Django 3.2.23 on 2023-12-31 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='nisn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='NISN'),
        ),
        migrations.AddField(
            model_name='peserta',
            name='thn_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ppdb.periodeppdb', verbose_name='Tahun Ajaran'),
        ),
    ]
