# Generated by Django 3.2.23 on 2023-12-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppdb', '0002_auto_20231204_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peserta',
            options={'verbose_name_plural': 'Peserta PPDB'},
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='alamat_ayah',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='alamat_ibu',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='alamat_wali',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='domisili_ayah',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='domisili_ibu',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='domisili_wali',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='hobi',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='keb_khusus',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='kodepos_ayah',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='kodepos_ibu',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='kodepos_wali',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='warga_ayah',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='warga_ibu',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='warga_siswa',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='warga_wali',
        ),
        migrations.AlterField(
            model_name='peserta',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='', max_length=15, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='nama',
            field=models.CharField(max_length=55, verbose_name='Nama Lengkap'),
        ),
    ]
