# Generated by Django 3.2.23 on 2024-01-25 13:45

from django.db import migrations, models
import ppdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('ppdb', '0003_auto_20240125_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='berkas',
            name='file_akta',
            field=models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_akta, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Akta Kelahiran'),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='file_ijazah',
            field=models.FileField(blank=True, help_text='(Jika sudah ada). File bisa berupa gambar atau pdf', max_length=255, null=True, upload_to=ppdb.models.Berkas.file_ijazah, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Ijazah Jenjang Sebelumnya'),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='file_kk',
            field=models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_kk, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Kartu Keluarga'),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='file_raport',
            field=models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_raport, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Nilai Raport Terakhir'),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='file_skhun',
            field=models.FileField(blank=True, help_text='(Jika sudah ada). File bisa berupa gambar atau pdf', max_length=255, null=True, upload_to=ppdb.models.Berkas.file_skhun, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='SKHUN'),
        ),
        migrations.AlterField(
            model_name='berkas',
            name='file_skl',
            field=models.FileField(help_text='File bisa berupa gambar atau pdf', max_length=255, upload_to=ppdb.models.Berkas.file_skl, validators=[ppdb.models.file_extension, ppdb.models.file_size], verbose_name='Surat Keterangan Lulus'),
        ),
    ]
